import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#111827" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  title: { fontSize: 24, fontWeight: "bold", color: "#F9FAFB" },

  // Wizard header
  wizardHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  backBtn: { marginRight: 12, padding: 4 },
  wizardTitle: { fontSize: 20, fontWeight: "bold", color: "#F9FAFB" },

  // Cards
  card: {
    marginHorizontal: 16,
    marginBottom: 10,
    padding: 14,
    backgroundColor: "#1F2937",
    borderRadius: 12,
  },
  cardSelected: { borderWidth: 2, borderColor: "#3B82F6" },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardTitle: {
    color: "#F9FAFB",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 4,
  },
  cardBody: { color: "#9CA3AF", fontSize: 13, marginBottom: 6 },
  cardMeta: { flexDirection: "row", gap: 16 },
  metaText: { color: "#6B7280", fontSize: 12 },
  metaExclude: { color: "#FBBF24", fontSize: 11 },
  excludeInfo: {
    color: "#FBBF24",
    fontSize: 12,
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  cardStats: { flexDirection: "row", gap: 16, marginTop: 4 },
  cardStat: { color: "#9CA3AF", fontSize: 13 },
  cardDate: { color: "#6B7280", fontSize: 11, marginTop: 4 },

  // Filter
  filterRow: { flexDirection: "row", alignItems: "center" },
  countBadge: {
    backgroundColor: "#374151",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  countText: { color: "#F9FAFB", fontSize: 16, fontWeight: "bold" },
  sectionLabel: {
    color: "#9CA3AF",
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    paddingHorizontal: 16,
    marginBottom: 8,
  },

  // Bottom bar
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#1F2937",
    borderTopWidth: 1,
    borderTopColor: "#374151",
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  limitRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  limitLabel: { color: "#D1D5DB", fontSize: 15 },
  limitInput: {
    backgroundColor: "#374151",
    color: "#F9FAFB",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    width: 100,
    textAlign: "center",
    fontSize: 16,
  },

  // Buttons
  primaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2563EB",
    paddingVertical: 14,
    borderRadius: 12,
    gap: 8,
  },
  primaryBtnText: { color: "#FFF", fontSize: 16, fontWeight: "600" },
  sendBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#059669",
    paddingVertical: 16,
    borderRadius: 12,
    gap: 8,
  },
  sendBtnText: { color: "#FFF", fontSize: 18, fontWeight: "700" },
  sendNowBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#059669",
    paddingVertical: 14,
    borderRadius: 12,
    gap: 8,
    marginBottom: 4,
  },
  sendNowBtnText: { color: "#FFF", fontSize: 16, fontWeight: "700" },
  secondaryBtn: {
    alignItems: "center",
    paddingVertical: 12,
    marginTop: 8,
  },
  secondaryBtnText: { color: "#3B82F6", fontSize: 15 },
  btnDisabled: { opacity: 0.5 },

  // Summary
  summaryCard: {
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 16,
    backgroundColor: "#1F2937",
    borderRadius: 12,
  },
  summaryTitle: { color: "#F9FAFB", fontSize: 18, fontWeight: "bold" },
  divider: {
    height: 1,
    backgroundColor: "#374151",
    marginVertical: 12,
  },
  summaryLabel: { color: "#9CA3AF", fontSize: 12, marginTop: 8 },
  summaryValue: { color: "#F9FAFB", fontSize: 16, fontWeight: "500" },
  previewBox: {
    backgroundColor: "#374151",
    padding: 12,
    borderRadius: 8,
    marginTop: 6,
  },
  previewText: { color: "#D1D5DB", fontSize: 14, lineHeight: 20 },
  previewInput: {
    backgroundColor: "#374151",
    color: "#D1D5DB",
    fontSize: 14,
    lineHeight: 20,
    padding: 12,
    borderRadius: 8,
    marginTop: 6,
    minHeight: 100,
    borderWidth: 1,
    borderColor: "#4B5563",
  },
  unsubRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
  },
  unsubLabel: { color: "#D1D5DB", fontSize: 14 },
  detailBody: {
    color: "#D1D5DB",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 8,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
  },
  detailLabel: { color: "#9CA3AF", fontSize: 13 },
  detailValue: { color: "#F9FAFB", fontSize: 13, fontWeight: "500" },

  // Status
  statusRow: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  stateBadge: { fontSize: 16, fontWeight: "700" },
  stateBadgeSmall: { fontSize: 13, fontWeight: "600" },
  progressBar: {
    height: 8,
    backgroundColor: "#374151",
    borderRadius: 4,
    overflow: "hidden",
    marginBottom: 16,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#34D399",
    borderRadius: 4,
  },
  statsGrid: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  statBox: { alignItems: "center" },
  statBoxValue: { fontSize: 22, fontWeight: "bold" },
  statBoxLabel: { color: "#6B7280", fontSize: 11, marginTop: 2 },

  // SIM picker
  simPickerCard: {
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 14,
    backgroundColor: "#1F2937",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#374151",
  },
  simPickerTitle: {
    color: "#F9FAFB",
    fontSize: 15,
    fontWeight: "600",
    marginBottom: 10,
  },
  simBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2563EB",
    paddingVertical: 12,
    borderRadius: 10,
    gap: 8,
    marginBottom: 8,
  },
  simSplitBtn: {
    backgroundColor: "#7C3AED",
  },
  simBtnText: { color: "#FFF", fontSize: 14, fontWeight: "600" },

  // Marketing stats
  marketingTitle: { color: "#F9FAFB", fontSize: 16, fontWeight: "600" },
  revenueRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#374151",
  },
  revenueLabel: { color: "#9CA3AF", fontSize: 14 },
  revenueValue: { color: "#34D399", fontSize: 20, fontWeight: "bold" },
  ratioRow: {
    flexDirection: "row",
    gap: 16,
    marginTop: 10,
  },
  ratioText: { color: "#9CA3AF", fontSize: 12 },

  // Empty state
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  emptyText: { color: "#6B7280", fontSize: 16, marginTop: 12 },
  emptySubtext: { color: "#4B5563", fontSize: 13, marginTop: 4 },

  // FAB
  fab: {
    position: "absolute",
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#2563EB",
    alignItems: "center",
    justifyContent: "center",
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
});
